### ISSUE TITLE
SDK is not managing any rate limiting / retry based on Aftership ratelimit headers. 

### ISSUE THREAD

**Issue by CharlyRien** [AfterShip/tracking-sdk-java#6]
Hello, 

I am currently trying to replace our home made Aftership http client by this SDK but the feature of rate limiting based on the status 429 and the headers is missing. Is that something you are planning to implement? 

I've seen in the code some private variables already set about it, not really used though. 

```
    private static final String RATE_LIMIT_RESET = "x-ratelimit-reset";
    private static final String RATE_LIMIT_LIMIT = "x-ratelimit-limit";
    private static final String RATE_LIMIT_REMAINING = "x-ratelimit-remaining";
```

Thanks :-)

**Comment by BossaGroove** [comment]
We do not implement the auto-retry feature within the SDK itself as we encourage the user to actually control the request throughput, rather than keep hammering our servers. Also, in the distributed system (more than 1 instance making the request), the auto-retry cannot provide a meaningful retrying mechanism until the user handle the request through adjustment.

**Comment by Bossa573** [comment]
We do not implement the auto-retry feature within the SDK itself as we encourage the user to actually control the request throughput, rather than keep hammering our servers. Also, in the distributed system (more than 1 instance making the request), the auto-retry cannot provide a meaningful retrying mechanism until the user handle the request throughput adjustment.

**Comment by CharlyRien** [comment]
You are correct, but as of today, we have no way to manage the rate limit headers using your SDK without manually overriding your HTTP client, for example.

Additionally, the 429 status code is not handled specifically by the SDK, which means that retrying by default may lead to further strain on the API.

I would appreciate having more informative details in the ApiException, such as when the rate limit will be reset or the rate limit headers, so I can calculate it myself.

Thank you for your time.

**Comment by Bossa573** [comment]
Hello @CharlyRien, 
we released a new version (7.1.0) and now the header values could be accessed via the `ApiException` object, for example:

```
try {
    // making API request
} catch (ApiException e) {
    for (Header header : e.getHeaders()) {
        System.out.println(header.getName() + ": " + header.getValue());
    }
} catch (Exception e) {
    e.printStackTrace();
}
```

And hence the headers could be accessed without overriding the HTTP client, please check and see if you need more fields / values, thank you very much

**Comment by CharlotteAuHaras** [comment]
Thanks. We will check that :-)

**Comment by CharlyRien** [comment]
Thanks, we will check that :)
